### PR TITLE
Removed extra comma at end of sql statement

### PR DESCRIPTION
**Pull request by jeking928**
This includes a few commits and reverts, but I think it's a clean pull request with just the one file change.

### CODE REVIEW

**Comment by DivaVocals** [comment]
Okay.. it's probably NOT the comma or the single quotes.. Code in question should look like this:

`    $sql = "INSERT IGNORE INTO ".TABLE_CONFIGURATION." (configuration_id, configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added, use_function, set_function) VALUES (NULL, 'COWOA Version', 'COWOA_VERSION', '2.6', 'Indicates the currently installed version of COWOA.', '".$cowoa_configuration_id."', 1, NOW(), NULL, 'zen_cfg_select_option(array(**\'2.6\'**),')";`

Note the part I bolded.. I did not properly escape the single quotes inside that function.. I will test tomorrow. Can you test this change as well.. If it works, you can revert your changes to this file..

**Comment by jeking928** [comment]
I did an install on a vanilla ZC 1.5.3 and no errors.  But isn't that last comma extra?  This one:
 'zen_cfg_select_option(array(\'2.6\')**,**')";
The values are separated by commas, but the last value does not need a comma at the end.

I tested without the comma and it also worked without error.

**Comment by DivaVocals** [comment]
I've looked at a BUNCH of other auto installers with single values inside that array, and that is the format they ALL use.. I would have to ask why or why not to include the trailing comma (since I don't know). IN FACT the idea to put the version inside that array is something I got from lhungil..He's SUPER picky (think ANAL :smile: in a GOOD way) about his code. I trust his judgement/reasoning on this.. So I just copied the technique and never questioned the WHY it's done this way, I just accepted that it IS done this way.. It got me the result I wanted, an un-editable version number.

**Comment by DivaVocals** [comment]
Gonna close this pull request.. Can you re-submit with just the changes to the readme?

**Comment by jeking928** [comment]
Well, I'm not one to argue that if it works both ways and lhungil uses one, there's probably a good reason.  The readme was just the tab heading change, very simple, but I will re-submit.

**Comment by DivaVocals** [comment]
Oh let me be clear.. I don't doubt that it works without the comma.. it's just that I'd like to know why it was included to begin with so WE can make the decision on the "right" way.. 'tis all.. :smile_cat:

**Comment by jeking928** [comment]
Maybe we should ask lhungil? I just sent him an email.

**Comment by DivaVocals** [comment]
Oh I was already doing that.. **lol**

**Comment by lhungil** [comment]
In Zen Cart's "/admin/configuration.php" the set_function is called inside an eval() with the current value and a ")" appended. So escaping the single quote and adding the comma results in the eval looking like:

$value_field = zen_cfg_select_option(array('2.6'), "2.6");

**Comment by DivaVocals** [comment]
Okaaaaaaaayyy.. :laughing: 

so the trailing comma is WRONG????

Sorry for being dense here.. :smiley_cat:

**Comment by lhungil** [comment]
Trailing comma is correct.

'zen_cfg_select_option(array(\'2.6\'),' . '"' . $configuration_value . '")';

**Comment by jeking928** [comment]
Um, call me confused :confused:

The sql statement up top has ten columns with a comma following all but the last.  It has ten values with a comma following all, *including* the last and seems to be missing the closing parenthesis for the values.  

I'm sure I'm not understanding something, just not sure what that is.

**Comment by DivaVocals** [comment]
Not true.. I do not have values in the set_function column for all of the configuration table inserts. Only those in which there is a dropdown list of values or radio button values.

The format is consistent each time
`'zen_cfg_select_option(array(\'true\', \'false\'),')";`

`'zen_cfg_select_option(array(\'true\', \'false\'),')";`

With regards to the line in question.. due to sleep deprivation and the lateness of the hour, I nearly had it right.. the errors you got when running the installer were due to my mea culpa and forgetting to escape the single quotes.. It now looks like this:
`zen_cfg_select_option(array(\'2.6\'),')";`

**Comment by jeking928** [comment]
Must be the *set_function* that is throwing me off.  A plain, vanilla INSERT statement needs balanced columns and values and a closing parenthesis.  I've got that part right, don't I?

**Comment by lhungil** [comment]
Just to clarify as I may have been a little unclear above.

The value in the set_function column in this case should have a trailing comma and have no closing parentheses. EX: 'zen_cfg_select_option(array(\'2.6\'),'

The SQL statement itself should not have a trailing comma.

**Comment by DivaVocals** [comment]
But each statement DOES have balanced columns and values.. and balanced parenthesis.

**Comment by DivaVocals** [comment]
The closing parenthesis closes the WHOLE statement.. not JUST that section..

**Comment by DivaVocals** [comment]
I get it now.. the comma IS needed.. look at how the value inserted into the set_function column..

if I understand Andrew's earlier response
$value_field = zen_cfg_select_option(array('2.6'), "2.6");

translates to a single radio button labeled "2.6" with a value of 2.6 when selected. And since there is only ONE value it is selected by default.

**Comment by jeking928** [comment]
A third look and I do see the balanced columns and values.  I realized the 'last comma' is actually within that last value (as you noted in your post above as I write this).  But I'm not seeing the balanced parentheses. See that screen shot.  I see the opening and closing parentheses for the columns and the opening parentheses for the values but not the closing.

image

**Comment by DivaVocals** [comment]
In YOUR fork they are NOT balanced.. In mine they are..

    **(**NULL, 'COWOA Version', 'COWOA_VERSION', '2.6', 'Indicates the currently installed version of COWOA.', '".$cowoa_configuration_id."', 1, NOW(), NULL, 'zen_cfg_select_option(array(\'2.6\'),'**)**";

**Comment by lhungil** [comment]
The red left parentheses is inside text (column value). The red right parentheses is closing the last blue circled left parentheses.

**Comment by DivaVocals** [comment]
And if it wasn't closed properly, you would get errors.. the fact that it's NOT erroring out says it's correct.. 

Also I use Programmer's Notepad which helps with syntax by color coding the text so you can see CLEARLY when your code is out of balance/incorrect/using wrong syntax.

**Comment by jeking928** [comment]
Well, ummm, I see now. Don't these things have a delete button anywhere?  :blush:

**Comment by DivaVocals** [comment]
Yep.. :laughing: if you're looking to undo this whole thread, you can click the "X" next to the edit icon for the comment you want to delete..

**Comment by jeking928** [comment]
Back into confusion mode..

From your post:
In YOUR fork they are NOT balanced.. In mine they are..

(NULL, 'COWOA Version', 'COWOA_VERSION', '2.6', 'Indicates the currently installed version of COWOA.', '".$cowoa_configuration_id."', 1, NOW(), NULL, 'zen_cfg_select_option(array(\'2.6\'),')";

I count four opening parenthesis and three closing parenthesis.  In my screen shot, the red highlighting indicated the last closing parentheses does not close the opening one in-front of the first NULL.

Sorry, I'm trying to understand but not.

**Comment by DivaVocals** [comment]
Please see both of Andrews posts.. he explains the "stray" parenthetical value and what the ouput is.. Trust me that the code is RIGHT otherwise you would get errors or some other undesireable effect.. I personally don't need to know WHY.. I just know that it DOES.. :smile_cat:

**Comment by jeking928** [comment]
I'll re-read them.  I have no doubt it is right! Just trying to understand the why.

**Comment by DivaVocals** [comment]
If you re-read what Andrew stated, the why is a little clearer..

**Comment by jeking928** [comment]
I do understate this part:
$value_field = zen_cfg_select_option(array('2.6'), "2.6");
I don't understand why the VALUES are not within balanced parenthesis.

**Comment by DivaVocals** [comment]
Well I'll leave you to solve this mystery then.. I don't HAVE to know WHY NOW.. :laughing: it's time for lunch and food is calling my name.. 

I bid you all adieu..

Next up.. refining the use of the Font Awesome icons..

**Comment by lhungil** [comment]
In the image posted...  The opening parentheses (in red) is inside a TEXT string. The closing parenthesis (in red) is outside the TEXT string. So the second opening parentheses (circled in blue) matches up with the closing parenthesis (in red).

So in closing, `'zen_cfg_select_option(array(\'2.6\'),'` is a TEXT string to be stored in the SQL column "set_function". The parentheses inside the TEXT string are just TEXT, not a grouping indicator for PHP or SQL.

**Comment by jeking928** [comment]
Thanks to both of your patience in explaining this to me.  I mostly get it, but feel I've beat this topic to death.  I'll do a little more exploring on my own.

**Pull request closed without merging**
